eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    preferIpAddress: true # default
    leaseRenewalIntervalInSeconds: 30 # default
    leaseExpirationDurationInSeconds: 90 # default
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} # default
      
