eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} # default
    preferIpAddress: true # default
    leaseRenewalIntervalInSeconds: 30 # default
    leaseExpirationDurationInSeconds: 90 # default
  
